# Generated by Django 3.2.7 on 2021-12-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mkp',
            name='id1',
        ),
        migrations.RemoveField(
            model_name='mkp',
            name='name',
        ),
        migrations.AddField(
            model_name='mkp',
            name='img',
            field=models.ImageField(null=True, upload_to='myimage/'),
        ),
    ]
