# Generated by Django 3.2.7 on 2021-12-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_auto_20211203_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='pid',
            field=models.IntegerField(null=True),
        ),
    ]
