# Generated by Django 3.2.7 on 2021-12-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0004_products_pid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='id',
        ),
        migrations.AlterField(
            model_name='products',
            name='pid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
