# Generated by Django 3.2.7 on 2021-12-03 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0007_alter_products_pid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mkp',
        ),
    ]
