# Generated by Django 3.2.7 on 2021-12-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0008_delete_mkp'),
    ]

    operations = [
        migrations.CreateModel(
            name='product2',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=50)),
                ('pimg', models.ImageField(null=True, upload_to='myimage')),
                ('pprice', models.IntegerField()),
            ],
        ),
    ]
