# Generated by Django 3.2.7 on 2021-12-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0009_product2'),
    ]

    operations = [
        migrations.CreateModel(
            name='uers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=50)),
                ('pimg', models.ImageField(null=True, upload_to='myimage')),
                ('pprice', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='product2',
        ),
    ]
