# Generated by Django 3.2.7 on 2021-12-03 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0010_auto_20211203_1847'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='uers',
            new_name='product',
        ),
    ]
